version: '3.8'

services:
  app:
    build: .
    ports:
      - "9090:9090"
    depends_on:
      - clickhouse
      - vault

  clickhouse:
    image: yandex/clickhouse-server:latest
    ports:
      - "9000:9000"
      - "8123:8123"
    volumes:
      - clickhouse-data:/var/lib/clickhouse

  vault:
    image: vault:1.9.0
    ports:
      - "8200:8200"
    volumes:
      - vault-data:/vault/data
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200

volumes:
  clickhouse-data:
  vault-data:
